#!/usr/bin/env python3
"""Verify that every locale under locales/ is complete and faithful.

Run from anywhere:  python3 tools/verify_locales.py [--strict] [--quiet]

Errors (exit status 1) are structural: a missing file, a missing topic, a
broken link, a slug left in English, a landing page that does not list every
topic, a country variant that differs from its base locale.

Warnings are content-fidelity heuristics that need a human look; they exit 0
unless --strict is given:
  - structure: a translation has a different number of headings, code fences,
    bullets or paragraphs than the English source (a sentence was dropped or
    merged);
  - figures: more than 30% of the numbers in the English source are missing
    from the translation (a worked example was rewritten rather than
    translated). Numbers are compared after normalising native digits and
    thousands separators, so "40.000", "40 000" and "४०,०००" all match 40,000.
    Numbers a language writes as words or with 万 notation can still trigger a
    false positive; check by eye.

The rules are in spec/index.md ("Locale completeness"). bin/test runs the
cheaper structural rules; this tool is the full audit.
"""
import collections
import os
import re
import sys
import unicodedata

TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCALES = os.path.join(TOP, "locales")
CANONICAL = "en-gb-oxendict"
DERIVED = {"en-001", "en-gb", "en-us"}  # generated by tools/localize.py
ENGLISH = DERIVED | {CANONICAL}
# Country variants / copies: byte-identical to their base locale.
VARIANTS = {
    "ar-eg": "ar-001", "hi-in": "hi-001", "es-es": "es-001", "pt-pt": "pt-001",
    "ru-ru": "ru-001", "fr-fr": "fr-001", "cy-gb": "cy-001", "de-001": "de-de",
    "sv-001": "sv-se", "nl-001": "nl-nl", "ur-001": "ur-pk", "da-001": "da-dk", "fi-001": "fi-fi",
    "it-001": "it-it", "tr-001": "tr-tr", "is-001": "is-is",
}
# Titles that are only an acronym or a proper name: the slug may equal English.
SLUG_MAY_EQUAL_ENGLISH = {"iso-ts-82304-2", "re-aim-framework"}
LANDING_SECTIONS = 8
# Figure warnings checked by hand and found to be formatting, not divergence:
# Arabic writes some figures as words (e.g. "the ninetieth percentile") and
# Chinese writes large figures with 万 (60万 = 600,000).
KNOWN_FALSE_FIGURE_WARNINGS = {
    ("ar-001", "digital-referral-turnaround-time"), ("ar-001", "time-to-intervention-rate"),
    ("ar-001", "user-retention-rate"), ("ar-eg", "digital-referral-turnaround-time"),
    ("ar-eg", "time-to-intervention-rate"), ("ar-eg", "user-retention-rate"),
    ("zh-cn", "marketing-efficiency-ratio"), ("zh-cn", "roi-and-voi"),
    ("zh-001", "marketing-efficiency-ratio"), ("zh-001", "roi-and-voi"),
    ("zh-tw", "marketing-efficiency-ratio"), ("zh-tw", "roi-and-voi"),
}
# Directories (not locales) allowed at the top of a locale: en-us keeps a
# non-book "communications" folder.
IGNORED_FILES = {("en-us", "communications")}

N = lambda s: unicodedata.normalize("NFC", s)
errors, warnings = [], []


def err(locale, msg):
    errors.append(f"{locale}: {msg}")


def warn(locale, msg):
    warnings.append(f"{locale}: {msg}")


def read(path):
    with open(path, encoding="utf8") as f:
        return f.read()


def digits(text):
    return "".join(
        str(unicodedata.decimal(c)) if unicodedata.category(c) == "Nd" else c for c in text
    )


def figures(text):
    text = re.sub(r"\]\([^)]*\)", "", text)
    text = re.sub(r"[,.  ٬٫، ](?=\d)", "", digits(text))
    return collections.Counter(re.findall(r"\d+", text))


def paragraphs(text):
    return len([p for p in re.split(r"\n\s*\n", text) if p.strip()])


def shape(text):
    return {
        "headings": len(re.findall(r"^#{1,6} ", text, re.M)),
        "code fences": text.count("```"),
        "bullets": len(re.findall(r"^- ", text, re.M)),
        "paragraphs": paragraphs(text),
    }


def main(strict=False, quiet=False):
    canonical_topics = sorted(os.listdir(f"{LOCALES}/{CANONICAL}/topics"))
    peer = {
        read(f"{LOCALES}/{CANONICAL}/topics/{t}/.locale-peer-id").strip(): t
        for t in canonical_topics
    }
    english = {t: read(f"{LOCALES}/{CANONICAL}/topics/{t}/index.md") for t in canonical_topics}
    locales = sorted(d for d in os.listdir(LOCALES) if os.path.isdir(f"{LOCALES}/{d}"))
    for loc in locales:
        base = f"{LOCALES}/{loc}"
        for name in ("index.md", ".locale-peer-id"):
            if not os.path.isfile(f"{base}/{name}") or os.path.getsize(f"{base}/{name}") == 0:
                err(loc, f"missing or empty {name}")
        if not os.path.islink(f"{base}/README.md") or os.readlink(f"{base}/README.md") != "index.md":
            err(loc, "README.md is not a symlink to index.md")
        subdirs = [d for d in os.listdir(base) if os.path.isdir(f"{base}/{d}") and (loc, d) not in IGNORED_FILES]
        if loc in ENGLISH:
            seg = "topics"
            if seg not in subdirs:
                err(loc, "no topics directory")
                continue
        else:
            if len(subdirs) != 1:
                err(loc, f"expected exactly one translated topics directory, found {subdirs}")
                continue
            seg = subdirs[0]
            if seg == "topics":
                err(loc, "topics directory name is not translated")
        found = {}
        for d in sorted(os.listdir(f"{base}/{seg}")):
            tdir = f"{base}/{seg}/{d}"
            if not os.path.isdir(tdir):
                err(loc, f"stray file in {seg}/: {d}")
                continue
            for name in ("index.md", ".locale-peer-id"):
                if not os.path.isfile(f"{tdir}/{name}") or os.path.getsize(f"{tdir}/{name}") == 0:
                    err(loc, f"{d}: missing or empty {name}")
            if not os.path.islink(f"{tdir}/README.md") or os.readlink(f"{tdir}/README.md") != "index.md":
                err(loc, f"{d}: README.md is not a symlink to index.md")
            try:
                topic = peer[read(f"{tdir}/.locale-peer-id").strip()]
            except (KeyError, OSError):
                err(loc, f"{d}: peer id does not belong to a canonical topic")
                continue
            if topic in found:
                err(loc, f"{d}: duplicate of topic {topic}")
            found[topic] = d
        missing = [t for t in canonical_topics if t not in found]
        if missing:
            err(loc, f"missing topics: {missing}")
        have = {N(d) for d in found.values()}
        if loc not in ENGLISH:
            same = [t for t, d in found.items() if N(d) == t and t not in SLUG_MAY_EQUAL_ENGLISH]
            if same:
                err(loc, f"slugs left in English: {same}")
            for d in found.values():
                if re.search(r"[\s/\\.:,()?*\"<>|]", d):
                    err(loc, f"slug contains a forbidden character: {d!r}")
        landing = read(f"{base}/index.md")
        links = [N(x) for x in re.findall(r"\]\(" + re.escape(seg) + r"/([^/)]+)/\)", landing)]
        if len(set(links)) != len(canonical_topics) or any(x not in have for x in links):
            err(loc, f"landing page links {len(set(links))} distinct topics (expected {len(canonical_topics)}) or links to a missing one")
        if len(re.findall(r"^## ", landing, re.M)) != LANDING_SECTIONS:
            err(loc, f"landing page has {len(re.findall(r'^## ', landing, re.M))} sections (expected {LANDING_SECTIONS})")
        for topic, d in found.items():
            text = read(f"{base}/{seg}/{d}/index.md")
            for x in re.findall(r"\]\(\.\./([^/)]+)/\)", text):
                if N(x) not in have:
                    err(loc, f"{d}: broken link ../{x}/")
            if loc in ENGLISH:
                continue
            want, got = shape(english[topic]), shape(text)
            diff = [f"{k} {want[k]}/{got[k]}" for k in want if want[k] != got[k]]
            if diff:
                warn(loc, f"{topic}: structure differs from English ({', '.join(diff)})")
            fe, ft = figures(english[topic]), figures(text)
            total, lost = sum(fe.values()), sum((fe - ft).values())
            if total and lost / total >= 0.30 and (loc, topic) not in KNOWN_FALSE_FIGURE_WARNINGS:
                warn(loc, f"{topic}: {lost}/{total} of the English figures are missing (worked example rewritten?)")
    for variant, base in VARIANTS.items():
        if variant in locales and base in locales:
            if os.system(f"diff -rq -x sitemap.xml '{LOCALES}/{base}' '{LOCALES}/{variant}' >/dev/null 2>&1") != 0:
                err(variant, f"is not identical to {base}")
    if os.system(f"python3 '{TOP}/tools/build_locale_sitemaps.py' --check") != 0:
        err("-", "a locale sitemap.xml is missing or stale: run python3 tools/build_locale_sitemaps.py")
    if not quiet or errors or (strict and warnings):
        for line in errors:
            print("ERROR  ", line)
        for line in warnings:
            print("WARNING", line)
    print(f"{len(locales)} locales checked: {len(errors)} errors, {len(warnings)} warnings")
    return 1 if errors or (strict and warnings) else 0


if __name__ == "__main__":
    sys.exit(main(strict="--strict" in sys.argv, quiet="--quiet" in sys.argv))
